
#### Usuarios API

GET http://localhost:8080/api/v1/usuarios

###
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
     "nombreUsuario": "Alan Turing",
     "email": "alan.fadga@gmail.com",
     "password": "password123"
}

###
GET http://localhost:8080/api/v1/usuarios/1

#### Partidos API

GET http://localhost:8080/api/v1/partidos?ubicacion=En%20el%20patio

###
POST http://localhost:8080/api/v1/partidos
Content-Type: application/json

{
  "cantidadDeJugadores": 10,
  "ubicacion": "En el patio"
}

###
GET http://localhost:8080/api/v1/partidos/2

###

PUT http://localhost:8080/api/v1/partidos/1/cancelar
Content-Type: application/json

{

}

###
GET http://localhost:8080/api/v1/partidos/1/jugadores

###

POST http://localhost:8080/api/v1/partidos/1/jugadores
Content-Type: application/json

{
  "usuarioId": 2,
  "confirmado": false
}