
#### Usuarios API

GET http://localhost:8080/api/v1/usuarios

###
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
     "nombreUsuario": "Juan pepe",
     "email": "alan.fadga@gmail.com",
     "password": "password123",
     "nivel": "AVANZADO",
     "deporteFavorito": {
            "id": 1
     }
}

###
GET http://localhost:8080/api/v1/usuarios/1


###
GET http://localhost:8080/api/v1/usuarios/1/partidos

###

PUT http://localhost:8080/api/v1/usuarios/2/partidos/152/confirmar
Content-Type: application/json

{
}

### Deportes API

GET http://localhost:8080/api/v1/deportes

###
POST http://localhost:8080/api/v1/deportes
Content-Type: application/json

{
    "nombre": "Fútbol 5"
}


#### Partidos API

GET http://localhost:8080/api/v1/partidos?ubicacion=En%20el%20patio

###
POST http://localhost:8080/api/v1/partidos
Content-Type: application/json

{
    "cantidadDeJugadores": 2,
    "ubicacion": "En el patio",
    "duracionEnMinutos": 90,
    "fechaComienzo": "2023-10-01T15:00:00",
    "deporte": {
        "id": 1
    }
}

###
GET http://localhost:8080/api/v1/partidos/152

###

PUT http://localhost:8080/api/v1/partidos/503/cancelar
Content-Type: application/json

{

}

###
GET http://localhost:8080/api/v1/partidos/152/jugadores

###

POST http://localhost:8080/api/v1/partidos/503/jugadores
Content-Type: application/json

{
  "usuarioId": 202,
  "confirmado": true
}